<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXSy9lrh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXSy9lrh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXSy9lrh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXSy9lrh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXSy9lrh\App_KernelDevDebugContainer([
    'container.build_hash' => 'XSy9lrh',
    'container.build_id' => 'd29de941',
    'container.build_time' => 1682123219,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXSy9lrh');
